# https://www.getzola.org/documentation/getting-started/configuration/

# The URL the site will be built for
base_url = "https://blog.momo.gg"

# The site title and description; used in feeds by default.
title       = "Thinking out loud"
description = "Blazingly fast, frequently hyperbolic and confidently incorrect opinions of knowing shit about fuck."

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
    # Whether to do syntax highlighting
    # Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
    highlight_code = true

[extra]
    # Put all your custom variables here
